[theme]
primaryColor="#3b82f6"
backgroundColor="#0f172a"
secondaryBackgroundColor="#1e293b"
textColor="#f8fafc"
font="sans serif"

[theme.sidebar]
widgetBackgroundColor="#1e293b"
widgetBorderColor="#334155"
skeletonBackgroundColor="#1e293b"

